### ISSUE TITLE
Fetch API

### ISSUE THREAD

**Issue by rishikesh2003** [rishikesh2003/blog#2]
i'm using api's for my blog post and dynamic routes. All things working correctly but when i go to a specific post and reload it didn't fetch data from the api.

**Comment by aymenhamada** [comment]
Did you find the issue ?

**Comment by aymenhamada** [comment]
I've looked at your code and it seems the problem is not that it didn't fetch data from the API,
the problem is that your are trying to use the data before they came back from the API.
Please take note that an API call is Asynchronous, you cannot use the data until you get it from the API.

When your app launch u've set an useffect which call the API and thats great

`  useEffect(() => {
    fetchData();
  }, []);
  const [posts, setPosts] = useState([]);
  const fetchData = async () => {
    const url = "https://run.mocky.io/v3/2cc5e901-012a-49c7-8418-fd0af3ad868d";

    const result = await fetch(url);
    const parsedData = await result.json();
    setPosts(parsedData);
  };
`
Now your Posts are defined after the API call return data, once you go to your blog route everything work cause your Posts  State are defined,  but when your refresh you loose all State and  the Useeffect trigger again, and again its Asyncrhonous so its not immediatly, homewer in your Post component you are using the data immediatly which return an error "Cannot read proprety of undefined".

The trick is to verify if your post are defined first before using it,
` <h1>{post && post.title}</h1>` instead of `<h1>{post.title}</h1>`

**Comment by rishikesh2003** [comment]
Thanks

**Comment by rishikesh2003** [comment]
issue fixed
